language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: 5.5
    - php: hhvm

env:
  - DB=mysql
  - DB=sqlite

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE zf2entityaudit;'; fi"
  - curl -s https://getcomposer.org/installer | php && php composer.phar update --prefer-source --dev

script:
  - phpunit
  - php coverage-checker.php clover.xml 90
