language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - curl -s https://getcomposer.org/installer | php && php composer.phar update --prefer-source --dev

script:
  - phpunit
  - php coverage-checker.php clover.xml 55