language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.3.3
    - php: hhvm
    - php: hhvm-nightly
    

env:
  - DB=mysql
  - DB=sqlite

before_script:
  - phpversion=$(phpenv version); if [[ $phpversion =~ 5\.3\.3.* ]]; then  curl -s https://getcomposer.org/installer | php &&  php composer.phar install --dev --prefer-source; else  curl -s https://getcomposer.org/installer | php && php composer.phar install --dev; fi;
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE zf2entityaudit;'; fi"
  
script:
  - phpunit
  - php coverage-checker.php clover.xml 92
