language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.3.3
    - php: hhvm
    - php: hhvm-nightly
    

env:
  - DB=mysql
  - DB=sqlite
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libssl-dev openssl
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE zf2entityaudit;'; fi"
  - curl -s https://getcomposer.org/installer | php && php composer.phar update --prefer-source --dev

script:
  - phpunit
  - php coverage-checker.php clover.xml 92
